(cl:defpackage cs1567p4-srv
  (:use )
  (:export
   "MAKENEWMAZE"
   "<MAKENEWMAZE-REQUEST>"
   "MAKENEWMAZE-REQUEST"
   "<MAKENEWMAZE-RESPONSE>"
   "MAKENEWMAZE-RESPONSE"
   "GETMAZEWALL"
   "<GETMAZEWALL-REQUEST>"
   "GETMAZEWALL-REQUEST"
   "<GETMAZEWALL-RESPONSE>"
   "GETMAZEWALL-RESPONSE"
   "CONSTANTCOMMAND"
   "<CONSTANTCOMMAND-REQUEST>"
   "CONSTANTCOMMAND-REQUEST"
   "<CONSTANTCOMMAND-RESPONSE>"
   "CONSTANTCOMMAND-RESPONSE"
  ))

